window.CARA_CONFIG = {
  API_BASE_URL: window.CARA_API_BASE_URL || '',
  TAX_RATE: 0.18,
  SHIPPING: {
    FEE: 150,
    FREE_THRESHOLD: 3000
  },
  URGENCY_DISCOUNT_PCT: 0.05,
  GIFT_WRAP_CHARGE: 99,
  LOYALTY: {
    POINTS_PER_RUPEE: 10,
    DEFAULT_BALANCE: 150
  },
  FEATURE_FLAGS: {
    ENABLE_DARK_MODE: true,
    ENABLE_WISHLIST: true
  }
};

window.CARA_COUPONS = {
  'CARA20': 20,
  'WELCOME10': 10
};
