name: Link Checker

on:
  pull_request:
    branches: [ main ]

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Broken HTML and MD Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --root-dir ${{ github.workspace }} --exclude "(linkedin\.com|twitter\.com|x\.com|github\.com/janavipandole|vercel\.app|localhost|jsdelivr\.net|cdnjs\.cloudflare\.com|stripe\.com|americanexpress\.com|mastercard\.com|paypal\.com|visa\.com)" --accept 429,403,999 './**/*.html' './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
